# Generated by Django 3.0.3 on 2020-02-15 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainmodules', '0002_auto_20200214_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='type',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
