# Generated by Django 3.0.3 on 2020-02-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainmodules', '0003_auto_20200215_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_assignment_set', to='trainmodules.Module'),
        ),
    ]
