# Generated by Django 3.0.3 on 2020-02-16 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
